### ISSUE TITLE
Runtime Exception is thrown when order of running effect stack is wrong

### ISSUE THREAD

**Issue by taojang** [etorreborre/eff-scalaz#2]
I'm playing a bit with Eff, but notice that it's not like the document says that effect could be run in different order.
In my code at the end the ```val res1 = ...``` will throw runtime exception :(

https://gist.github.com/taojang/582e50e1834e3dd095f676c8c75316a5

**Comment by etorreborre** [comment]
Thanks for reporting this bug, a very important one indeed. Please find the fix in `1.1-20160403152816-4e86b39`.
